Repository Gyanthakur/GFG_POTD, pull requests merged in 2025-10, with the labels that each got.

#234 1 October 25
  october25/01/10/2025.cpp
Labels: hactoberfest, hacktoberfest, Hactoberfest-accepted

#239 feat: Add optimized O(n²) solution for maximum sum of two smallest elements in subarrays
  october_2024/POTD_12_OCT_2024_TwoSmallestsInEverySubarray.cpp
  october_2024/POTD_29_OCT_2024_QUICKSORT_ON_LINKED_LIST.cpp
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest_2024

#238 Added GFG_POTD_Sep_2025
  September_2025/(01-Sep)Sum-Of-Mode.py
  September_2025/(02-Sep)Swap-Kth-Nodes-from-End
  September_2025/(03-Sep)Reverse-aDoubly-Linked-List.py
  September_2025/(04-Sep)Linked-List-Group-Reverse.py
  September_2025/(05-Sep)Sort-aLinked-List-of-0's,1's-and2's.py
  September_2025/(06-Sep)Find-Length-of-loop.py
  September_2025/(07-Sep)Merge-KSorted-Linked-Lists.py
  September_2025/(08-Sep)Merge-Sort-for-Linked-List.py
  September_2025/(09-Sep)Assign-Mice-Holes.py
  September_2025/(10-Sep)Largest-Number-in-One-Swap.py
  September_2025/(11-Sep)Minimum-Jumps.py
  September_2025/(12-Sep)Minimize-the-Heights-II.py
  September_2025/(13-Sep)Minimum-Cost-to-Cut-a-Board-into-Squares.py
  September_2025/(14-Sep)Gas-Station.py
  September_2025/(15-Sep)String-Stack.py
  September_2025/(16-Sep)Postfix-Evaluation.py
  September_2025/(17-Sep)Decode-the-String.py
  September_2025/(18-Sep)Next-Greater-Element-in-Circular-Array.py
  September_2025/(19-Sep)Min-Add-to-Make-Parenthesis-Valid.py
  September_2025/(20-Sep)Longest-Subbarray-Length.py
  September_2025/(21-Sep)Max-Rectangle.py
  September_2025/(22-Sep)Max-of-Min-of-Every-Size.py
  September_2025/(23-Sep)Queue-Reversal.py
  September_2025/(24-Sep)Design-Min-Max-Queue.py
  September_2025/(25-Sep)Generate-Binary-Numbers.py
  September_2025/(26-Sep)Rotate-Deque-By-K.py
  September_2025/(27-Sep)Minimum-K-Consecutive-Bit-Flips.py
  September_2025/(28-Sep)Longest-Bounded-Difference-Subarray.py
  September_2025/(29-Sep)Maximum-SubArray-Sum2.py
  September_2025/(30-Sep)Generate-All-Binary-Strings.py
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest_2024

#243 Added the py version of the solution
  October_2025/potd_02_10_2025.py
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest_2024

#241 done adding potd.
  oct_2025/oct_1st_2025/Solution.cpp
  oct_2025/oct_1st_2025/Solution.java
  oct_2025/oct_1st_2025/ques.txt
  oct_2025/oct_2nd_2025/Solution.cpp
  oct_2025/oct_2nd_2025/Solution.java
  oct_2025/oct_2nd_2025/ques.txt
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest_2024

#235 I have added code for gfg potd 2025 of 1 OCT
  october25/01/10/potd_1_10_2025.java
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest_2024

#244 Revert "done adding potd."
  oct_2025/oct_1st_2025/Solution.cpp
  oct_2025/oct_1st_2025/Solution.java
  oct_2025/oct_1st_2025/ques.txt
  oct_2025/oct_2nd_2025/Solution.cpp
  oct_2025/oct_2nd_2025/Solution.java
  oct_2025/oct_2nd_2025/ques.txt
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest_2024

#249 Added cpp solution of gfg_potd_03_10
  October_2025/potd_03_10_2025.cpp
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest_2024

#246 Feature/august2025
  August_2025/potd_26_08_25.py
  August_2025/potd_27_08_25.py
  August_2025/potd_28_08_25.py
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest_2024

#250 Update autoLabling.yml
  .github/workflows/autoLabling.yml
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest_2024

#251 aug-potd
  August_2025/(01-Aug)Balancing Consonants and Vowels Ratio.cpp
  August_2025/(02-Aug)Longest Subarray with Majority Greater than K.cpp
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest_2025

#254 Added python soln of GFG_POTD03_10
  October_2025/potd_03_10_2025.java
  October_2025/potd_03_10_2025.py
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest_2025

#253 Added java soln of GFG_POTD03_10
  October_2025/potd_03_10_2025.java
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest_2025

#257 adding cpp,java,py solution of 4 october 2025 potd
  October_2025/potd_04_10_2025.cpp
  October_2025/potd_04_10_2025.java
  October_2025/potd_04_10_2025.py
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest_2025

#248 solved
  POTD_3_OCT_2025_POSSIBLE_WORDS_FROM_PHONE_DIGIT.py
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest_2024

#264 Added py and java solution of GFG_POTD_05_10
  October_2025/potd_05_10_2025.java
  October_2025/potd_05_10_2025.py
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest_2025

#267 Rat in a Maze
  Rat_in_a_Maze.java
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest_2025

#269 The Knight's tour problem
  October_2025/potd_06_10.java
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest_2025

#278 Added 30_AUG_2025_CelebrityProblem.cpp (GFG POTD)
  August_2025/potd_30_08_25.cpp
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest_2025

#275 calculating area of circle and rectangle using c++
  calculating area of circle and rectangle using c++
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest_2025

#272 Added GFG POTD of 6 OCT
  october25/01/10/potd_6_10_2025.java
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest_2025

#270 Added cpp solution of GFG POTD_06_10_2025
  October_2025/potd_06_10_2025.cpp
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest_2025

#281 Added potd 8 oct. 2025
  October_2025/potd_08_10_2025.py
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest_2025

#279 calculating simple interest
  simple interest
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest_2025

#282 Update PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest_2025
